### ISSUE TITLE
Babylon finality gadget contract `schema` sync

### ISSUE THREAD

**Issue by bap2pecs** [babylonchain/babylon-finality-gadget#2]
when [Babylon finality gadget contract](https://github.com/babylonchain/babylon-contract/tree/main/contracts/op-finality-gadget)  interface is modified, we also need to modify this repo accordingly. For example, if `is_enabled` query is renamed, it will break the sdk

we should have a way to make sure they are in sync

one way is to paste https://github.com/babylonchain/babylon-contract/blob/main/contracts/op-finality-gadget/schema/raw/query.json here

**Comment by bap2pecs** [comment]
> Is there a plan to move the Babylon finality gadget contract to this repo?

I think we should since it's part of the DA. wdyt? @SebastianElvis @maurolacy

**Comment by SebastianElvis** [comment]
> > Is there a plan to move the Babylon finality gadget contract to this repo?
> 
> I think we should since it's part of the DA. wdyt? @SebastianElvis @maurolacy

Sounds good to me

**Comment by bap2pecs** [comment]
this is not needed anymore since now we have e2e tests in the FP repo to glue everything together.

let's imagine the CW contract is modified. then we compile a new binary and update the FP repo `bytecode` folder. if the new binary is not compatible w the SDK, e2e tests will fail so we can easily detect that and make the changes in this SDK repo accordingly
