### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by parketh** [babylonchain/babylon-finality-gadget#8]
We should rename this repo to better reflect its contents:

- CW finality gadget contracts
- SDK for interacting with contracts
- Interfaces for fetching VP from Babylonchain
- EOTS verification logic

Perhaps something like `op-finality-gadget`

**Comment by bap2pecs** [comment]
I think it's probably fine to keep its current name as in the future we might add support for Arb, CDK, zkSync and etc

feel free to reopen for further discussion
